apiVersion: v1
kind: Service
metadata:
  name: glue_database
spec:
  selector:
    app: glue_database
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
